import { createSlice } from "@reduxjs/toolkit";

// Rich local crop database — no API key needed
export const CROP_DB = [
  {
    id: "wheat",
    name: "Wheat",
    emoji: "🌾",
    category: "Cereal",
    season: "Rabi",
    sowingMonths: [10, 11, 12],
    harvestMonths: [3, 4],
    tempMin: 10,
    tempMax: 25,
    tempIdeal: 18,
    rainMin: 300,
    rainMax: 700,
    soilTypes: ["Loamy", "Clay-loam"],
    duration: "120-150 days",
    waterNeed: "Moderate",
    npk: { n: 120, p: 60, k: 40 },
    diseases: ["Rust", "Smut", "Blight"],
    pests: ["Aphids", "Armyworm"],
    yield: "3-5 t/ha",
    marketPrice: "₹2015/quintal (MSP)",
    tips: [
      "Use certified seeds for better germination",
      "Apply first irrigation at crown root initiation stage",
      "Monitor for yellow rust after tillering",
    ],
    stages: ["Germination (0-7d)", "Tillering (21-45d)", "Jointing (50-70d)", "Heading (80-100d)", "Ripening (110-150d)"],
  },
  {
    id: "rice",
    name: "Rice",
    emoji: "🌾",
    category: "Cereal",
    season: "Kharif",
    sowingMonths: [6, 7],
    harvestMonths: [10, 11],
    tempMin: 22,
    tempMax: 35,
    tempIdeal: 30,
    rainMin: 1000,
    rainMax: 2000,
    soilTypes: ["Clay", "Silty-clay"],
    duration: "100-150 days",
    waterNeed: "High",
    npk: { n: 100, p: 50, k: 50 },
    diseases: ["Blast", "Sheath blight", "Bacterial leaf blight"],
    pests: ["Stem borer", "Brown planthopper", "Gall midge"],
    yield: "4-6 t/ha",
    marketPrice: "₹2183/quintal (MSP)",
    tips: [
      "Transplant at 3-4 leaf stage for best results",
      "Maintain 5cm standing water during tillering",
      "Use integrated pest management for stem borer",
    ],
    stages: ["Nursery (0-25d)", "Transplanting (25-35d)", "Tillering (35-65d)", "Panicle initiation (65-85d)", "Ripening (85-150d)"],
  },
  {
    id: "cotton",
    name: "Cotton",
    emoji: "🌿",
    category: "Cash Crop",
    season: "Kharif",
    sowingMonths: [5, 6],
    harvestMonths: [10, 11, 12],
    tempMin: 20,
    tempMax: 40,
    tempIdeal: 30,
    rainMin: 500,
    rainMax: 1000,
    soilTypes: ["Black cotton soil", "Deep loamy"],
    duration: "150-180 days",
    waterNeed: "Moderate",
    npk: { n: 80, p: 40, k: 40 },
    diseases: ["Wilt", "Boll rot", "Leaf curl virus"],
    pests: ["Bollworm", "Whitefly", "Jassid"],
    yield: "1.5-2.5 t/ha",
    marketPrice: "₹6620/quintal (MSP)",
    tips: [
      "Plant Bt cotton for bollworm resistance",
      "Avoid water logging during flowering",
      "Monitor whitefly for leaf curl virus",
    ],
    stages: ["Germination (0-10d)", "Square initiation (40-60d)", "Flowering (60-90d)", "Boll formation (90-120d)", "Maturity (150-180d)"],
  },
  {
    id: "maize",
    name: "Maize",
    emoji: "🌽",
    category: "Cereal",
    season: "Kharif / Rabi",
    sowingMonths: [6, 7, 10, 11],
    harvestMonths: [9, 10, 2, 3],
    tempMin: 18,
    tempMax: 35,
    tempIdeal: 28,
    rainMin: 500,
    rainMax: 900,
    soilTypes: ["Sandy-loam", "Loamy"],
    duration: "90-120 days",
    waterNeed: "Moderate",
    npk: { n: 120, p: 60, k: 40 },
    diseases: ["Downy mildew", "Stalk rot", "Leaf blight"],
    pests: ["Fall armyworm", "Stem borer", "Aphids"],
    yield: "5-8 t/ha",
    marketPrice: "₹1870/quintal (MSP)",
    tips: [
      "Maintain proper plant spacing (75×25 cm)",
      "Apply nitrogen in split doses",
      "Irrigate at tasseling and silking stages",
    ],
    stages: ["Germination (0-5d)", "Seedling (5-20d)", "Vegetative (20-55d)", "Tasseling (55-75d)", "Grain fill (75-120d)"],
  },
  {
    id: "soybean",
    name: "Soybean",
    emoji: "🫘",
    category: "Legume",
    season: "Kharif",
    sowingMonths: [6, 7],
    harvestMonths: [9, 10],
    tempMin: 20,
    tempMax: 32,
    tempIdeal: 27,
    rainMin: 450,
    rainMax: 700,
    soilTypes: ["Well-drained loamy", "Clay-loam"],
    duration: "90-110 days",
    waterNeed: "Moderate",
    npk: { n: 20, p: 60, k: 40 },
    diseases: ["Pod blight", "Yellow mosaic", "Charcoal rot"],
    pests: ["Girdle beetle", "Stem fly", "Thrips"],
    yield: "1.5-2.5 t/ha",
    marketPrice: "₹4600/quintal (MSP)",
    tips: [
      "Seed treatment with Rhizobium reduces N-fertilizer need",
      "Avoid waterlogging during pod filling",
      "Monitor yellow mosaic virus via whitefly control",
    ],
    stages: ["Germination (0-7d)", "Vegetative (7-35d)", "Flowering (35-60d)", "Pod fill (60-90d)", "Maturity (90-110d)"],
  },
  {
    id: "potato",
    name: "Potato",
    emoji: "🥔",
    category: "Vegetable",
    season: "Rabi",
    sowingMonths: [10, 11],
    harvestMonths: [1, 2, 3],
    tempMin: 10,
    tempMax: 24,
    tempIdeal: 18,
    rainMin: 400,
    rainMax: 600,
    soilTypes: ["Sandy-loam", "Loamy"],
    duration: "70-120 days",
    waterNeed: "Moderate-High",
    npk: { n: 180, p: 80, k: 150 },
    diseases: ["Late blight", "Early blight", "Wilt"],
    pests: ["Colorado beetle", "Aphids", "Cutworm"],
    yield: "20-30 t/ha",
    marketPrice: "₹800-1200/quintal (market)",
    tips: [
      "Use certified seed tubers free from disease",
      "Earth up at 30 days to prevent greening",
      "Apply fungicide prophylactically for late blight",
    ],
    stages: ["Sprouting (0-15d)", "Vegetative (15-40d)", "Tuber initiation (40-70d)", "Bulking (70-100d)", "Maturity (100-120d)"],
  },
  {
    id: "tomato",
    name: "Tomato",
    emoji: "🍅",
    category: "Vegetable",
    season: "All seasons",
    sowingMonths: [1, 2, 6, 7, 10, 11],
    harvestMonths: [3, 4, 9, 10, 1, 2],
    tempMin: 15,
    tempMax: 35,
    tempIdeal: 25,
    rainMin: 400,
    rainMax: 600,
    soilTypes: ["Well-drained loamy", "Sandy-loam"],
    duration: "90-120 days",
    waterNeed: "Moderate",
    npk: { n: 100, p: 60, k: 80 },
    diseases: ["Early blight", "Late blight", "Wilt", "Mosaic"],
    pests: ["Fruit borer", "Whitefly", "Leaf miner"],
    yield: "25-40 t/ha",
    marketPrice: "₹600-2000/quintal (market variable)",
    tips: [
      "Stake plants at 30cm height for support",
      "Mulching reduces soil-borne diseases",
      "Spray calcium foliar to reduce blossom end rot",
    ],
    stages: ["Nursery (0-25d)", "Transplanting (25-35d)", "Vegetative (35-55d)", "Flowering (55-75d)", "Fruiting (75-120d)"],
  },
  {
    id: "sugarcane",
    name: "Sugarcane",
    emoji: "🎋",
    category: "Cash Crop",
    season: "Annual",
    sowingMonths: [2, 3, 10, 11],
    harvestMonths: [10, 11, 12, 1, 2],
    tempMin: 20,
    tempMax: 38,
    tempIdeal: 30,
    rainMin: 1000,
    rainMax: 1500,
    soilTypes: ["Deep loamy", "Clay-loam"],
    duration: "12-18 months",
    waterNeed: "High",
    npk: { n: 250, p: 60, k: 120 },
    diseases: ["Red rot", "Smut", "Wilt"],
    pests: ["Pyrilla", "Top borer", "Root borer"],
    yield: "60-100 t/ha",
    marketPrice: "₹340/quintal (SAP)",
    tips: [
      "Use 3-budded setts for planting",
      "Ratoon crop gives lower input cost",
      "Intercropping with legumes reduces weed",
    ],
    stages: ["Germination (0-30d)", "Tillering (30-90d)", "Grand growth (90-270d)", "Ripening (270-365d)", "Maturity (365-540d)"],
  },
  {
    id: "mustard",
    name: "Mustard",
    emoji: "🌼",
    category: "Oilseed",
    season: "Rabi",
    sowingMonths: [10, 11],
    harvestMonths: [2, 3],
    tempMin: 10,
    tempMax: 25,
    tempIdeal: 18,
    rainMin: 200,
    rainMax: 400,
    soilTypes: ["Sandy-loam", "Loamy"],
    duration: "110-140 days",
    waterNeed: "Low",
    npk: { n: 80, p: 40, k: 40 },
    diseases: ["White rust", "Downy mildew", "Alternaria blight"],
    pests: ["Aphids", "Painted bug", "Sawfly"],
    yield: "1.5-2.5 t/ha",
    marketPrice: "₹5650/quintal (MSP)",
    tips: [
      "Sow at optimum time for maximum oil content",
      "Apply sulphur fertilizer for yield boost",
      "Monitor aphids at pod formation stage",
    ],
    stages: ["Germination (0-7d)", "Rosette (7-30d)", "Bolting (30-55d)", "Flowering (55-75d)", "Maturity (110-140d)"],
  },
];

const savedCrops = () => {
  try { return JSON.parse(localStorage.getItem("myFarmCrops") || "[]"); }
  catch { return []; }
};

const cropSlice = createSlice({
  name: "crops",
  initialState: {
    all: CROP_DB,
    myFarm: savedCrops(),
    selected: null,
    searchQuery: "",
    filterCategory: "All",
    filterSeason: "All",
    sortBy: "name",
    page: 1,
    perPage: 6,
  },
  reducers: {
    selectCrop(state, { payload }) { state.selected = payload; },
    clearSelected(state) { state.selected = null; },
    setSearch(state, { payload }) { state.searchQuery = payload; state.page = 1; },
    setFilterCategory(state, { payload }) { state.filterCategory = payload; state.page = 1; },
    setFilterSeason(state, { payload }) { state.filterSeason = payload; state.page = 1; },
    setSortBy(state, { payload }) { state.sortBy = payload; },
    setPage(state, { payload }) { state.page = payload; },
    addToFarm(state, { payload }) {
      if (!state.myFarm.find(c => c.id === payload.id)) {
        const entry = { ...payload, addedAt: new Date().toISOString(), fieldSize: 1, notes: "" };
        state.myFarm.push(entry);
        localStorage.setItem("myFarmCrops", JSON.stringify(state.myFarm));
      }
    },
    removeFromFarm(state, { payload }) {
      state.myFarm = state.myFarm.filter(c => c.id !== payload);
      localStorage.setItem("myFarmCrops", JSON.stringify(state.myFarm));
    },
    updateFarmEntry(state, { payload }) {
      const idx = state.myFarm.findIndex(c => c.id === payload.id);
      if (idx !== -1) { state.myFarm[idx] = { ...state.myFarm[idx], ...payload }; }
      localStorage.setItem("myFarmCrops", JSON.stringify(state.myFarm));
    },
  },
});

export const {
  selectCrop, clearSelected, setSearch, setFilterCategory, setFilterSeason,
  setSortBy, setPage, addToFarm, removeFromFarm, updateFarmEntry,
} = cropSlice.actions;
export default cropSlice.reducer;
